language: objective-c
osx_image: xcode9.2

branches:
  except:
    - /^dev(.*)$/

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform mac --no-use-binaries --cache-builds
script:
  - xcodebuild clean build -project AMM.xcodeproj -target AMM
  - xcodebuild test -project AMM.xcodeproj -scheme AMM

before_deploy:
  # package release into dmg
  - release_dir=build/Release
  - release_name=AMM_${TRAVIS_TAG}
  - dmg_path=${release_dir}/${release_name}/${release_name}.dmg
  - mkdir ${release_dir}/${release_name} && mv ${release_dir}/AMM.app $_ && ln -s /Applications $_/
  - hdiutil create ${dmg_path} -volname ${release_name} -srcfolder ${release_dir}/${release_name}
deploy:
  provider: releases
  api_key:
    secure: "OBX7vxxgpc9Hns1KaOrmD1BBQ4ML05kjPgBC9B0XSd3owblG+NICVXq5zyllbKCoY6wyqMf3zdBRtueSdp9sNNIGWZeAUW6pOdg87D9Fj+FhsT+U4N1rhYbv4vo3Olt5b+5BKygM+oxEbXQuo2WmqWyaHpiUdFxlFIsFbeNFiZYlo4JKZaPw3z6M8gY3LCIdPhBLuy6Yz74DwVPwhJrcfa7cOjGDV3YEgsH96EV/garlVFoupB4bXUdS4fztNQp+dqWVegUBwOTtXP3E8e7PB4O4PSAB0vBO+QF0vCRhYFINT8xRJ79+HwsXIb47Glkv77DAfYllAWcV++Ldn/eSUjh+hjUIrP4zyhBPr18VZ0vGaZN5cVOqZFwU/lZdZ+jWA0GUs+HY+RmDwHpDtxhQ5n1/XePl62Ek/rUhSBgjcUg8/YmC21U4D3OIblZDRZuVVsMmu+vVmIWQdJGMDa2qlTzF0HFCW/dtJS5JR8jwnp5//+ivbYsZ3x8y6N2jm+UA9PmQk99mTW31pjGspF2o6Lnkt4Lb3+9YtW1wY16xNc3C30ftcQ9y5CNfQXSjLGkIgQNIJYA9hmy/imz0v0fwW0TQ6L21Zzwk3xi9fkgNeOOGYK3zHtvbTz3uwAHKCfGFaTbsouEJ7bw0cjL1L7bDaQ1xuvzoH+IKUdE4KxarCpk="
  file: $dmg_path
  skip_cleanup: true
  on:
    repo: 15cm/AMM
    all_branches: true
    tags: true
